apiVersion: ENC[AES256_GCM,data:u1o=,iv:zUztGgk61PMbB2jAdLScxrYB4iEJDN4ZrVCelm4SuvE=,tag:OOIDS4jNQLR0YREhwVgwvw==,type:str]
kind: ENC[AES256_GCM,data:fTydtwKO,iv:H4odzNKYuwqrjUMSaSLR+sEE+sl8PaUroExAUG7WBDE=,tag:jrwFsyG2oyOr8kaPqxPARQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xKB6//PnJC6g6PY=,iv:DDAlV/vByA/CybfkqgaO0FM4Hr//pDgaYpilGAqQYlM=,tag:ZPLRLdGLCAbg9evhOuZf9A==,type:str]
    namespace: ENC[AES256_GCM,data:5nK56W+NB9Kdnjw=,iv:dzhtD2ocO8Ii/GSN4301TpyYKOaHuNt7Q8lJERk/qvA=,tag:RvyiChPcEIkhcvD+aSPIcg==,type:str]
stringData:
    identity: ENC[AES256_GCM,data:XjTW4/zJNfng+6aBYam5MDONBNlJ0kkf8mqiO/7V65AuvdoRk+Hdy5OcP4/cJaSpK+rHzf+dAvi42kfjdrbzGSWymoyZekiM/IOPuy3oLuYNs99YsyGVwV6cSW8GxaU5T1ZeO8hPL/oqiKNrH8BqQ1z8CAKBs1Kuh0KHvWrTIkMdCFWpjagBI6xvj7oC6hcMzDfnJEckA9IOLQGk6CmCmvfQnLwQKGViJX0K4xKy8EELXemM7LELhkRARxmSmgB3dUBsU+8GHpudl3TU5VafFRbBEKB4x3OMrvBp74/qFICmiWeAtHplH6+A3tJ9FM8Uf1tDJfvt285UjsabvRvc2Zk060iGyt5DMvOk+YTnhQI1r26gAVroOCcKHWAHeuJde1pOwj6GYVjv0Wjjz8rXSOZXWpYbrvFX7eWgAWexScXtxW8DuzQI4/Uu2uKKBVncDC0+W9RPM2XuS+9hyE+kI55f6v+BXmSEjIKgbWLdFfUWv/QfCnCiMePUAqxzaMV4OFFYVm30bZHTVlLHDht+RJDQ2f+w74/Lvr2g,iv:PupZQHCBA+BrRqodcZv9MnncTe6dIEq1hjEis0g3ZEc=,tag:DlmoExvGDB04ywD3ivbmXA==,type:str]
    identity.pub: ENC[AES256_GCM,data:MgDHI6MkkUs/u9ILErQxTQimyA3OSPUNEf0inDE16QFFoko/uF1sk0ku5rw2UluDFlOVYJyfd9ziIE41CXwHUyKA6R5zS2MnhQMLqvzunybz,iv:bIgIP/bS6QgDwEGKQzGSBzF1wdCUL0TNYxXLsejJ0jw=,tag:I/JFNneEBQlUiuF8pTB2fA==,type:str]
    known_hosts: ENC[AES256_GCM,data:MbORhsPsKHIvMfWyzPsKMM/GEjwhrdPQ8pQFUR0DrgzbpXZ45I9Otzs77LoLFSZ9GvXGPRmkLKV7JN/rt1jz1kX7yjQSWktBEl6gq7GYEpuHBR7lGOjQWMeeaPibaifAomxOToPfTQHe9NDRHsJu67Ut2dwANAeaEwunoVNfM00g1T8LBHqiKcBTJHCpuixLf3SVzEOmcEG+T+Jux0Fa/AWNBSoSndvejeBX,iv:6YS5v7Kco1eeQDrYivrwQJA9IeC9xkHL8FBMnTV/uY0=,tag:8FqDa0bsDZtSLRnaBaQNcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK0VuemZPaVpPSE5UbkFV
            UjZZSW0yd3c0NVlSNEpzeTMrbUk1S1NIK1VVCktnaWtMWjdVaWhQYkZZSVVWdEVZ
            ejgyN253SzdCcmpaU2gvb2xkTHJleG8KLS0tIElXVU9Na1ZPU0FlZGw2dTJ4eG93
            KzJ2d3lUMExRbm5XcVNCdzNOMXp6UDQK0/Up2G9mQJhAWhwVeP8+tj43mk8shSgG
            F5Zk/dF7eCYYbj7qfLZmYhIjBgKLPSYnoYCYPB5r6tQZ0AOT89IfHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    lastmodified: "2026-09-07T16:28:07Z"
    mac: ENC[AES256_GCM,data:E5TlD50PKRQCpBjEFMpR9y3riZkw/+XOiTKZKkVQDP9/JFEmvi1mW88Z2PxyKKo1ak1H5hlR7kFy+6tGE5zxeOrdXnf27J4VWDYmASNfNK7Wj+2jwh2zfwjp8YkiUlg1uAI2WkJlAxNM/jkBZgAIayVl7WAxu5xZ72wp1Lbg9gY=,iv:qt+YfQfDVm3465A9MpyOEVpvcZCD2uHUkd7c1dZ5RHI=,tag:Mm9dnRLBu6I8dzgl3j4Dng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
