apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EsIl6nR/oZh9DD2MLwLiKYgshltF10a78Te+AM0eZqOsO2lOU9SDQRqGzHKycD+eabjV7ZmOYsh+FWfe3EB8V8o98bYJcIwK5GiMgJ7J6OSunts6uHcI4kxQT2oFI1FBW0P+Qg0IlsBRyPgorRe8UoVRzLiJzUFBAqu3j5B42oPbI8XmnudP2Ie95d1BwMZ39y3CbRm9YNIUZ/aKLOwFmzRraA57DtjL2B37t84yjko0cCzCwLMoxsx+hc7iKLlFwsieEg6Bob3P68P4ih+C1eNR6A2/h3M0t9q09PnwRxb6WaQ/LB291cHyjO6edN1jSJiQwAJNOgApxsDv0S+jOeYXNpeVUteLZGFNH8Lxdp02uuSFXr8vKxZI52TU3OiIa0++1IBUsD+bCCj58ctdnnVu9PrBW6eGp9jjAsPPEHKmK9DvX1nbAAEhsLXrYA0M7LNTkrTAWrWMFJZi6gXpIKxsC21eB0jz+b/3KKEjo/YXMZyHcQXCxAE0yIH016qaI9ZwYK0UL+SAQeWkflITFhFYO7fYtFISslf3,iv:3Lwaw7kvaJCV3K91PO7d9i+ni27ja9l4uyql2sfkq3Y=,tag:+YMFvxsjUIxrmG3ZCr96sQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:yzrNdLVPuKMB64QnclMB/F3OGyjh/SGp1qxlZzLJkoGtq7lV4gtTcncjh9bEs2+i1OKHAN5rjKvWaKvPunRxwNQQSdiOxuJSVQrvZtQu8zcx,iv:LLFyPE2s70eIiz5C9nwzU6FoKoL9CgKbYyuXAZ2jzuo=,tag:fir+Qug2uzBQKE0gYsDvJw==,type:str]
    known_hosts: ENC[AES256_GCM,data:CLv9A71z28JM3wzM3tfFqUMGb6X9IKnNjTmP6WSVbOYIPRAFioEKyONwS8LbrHndUQolW3swwtcxl6c6I2ZVtu7C5UdfBNim9W2NhlAJbcQfK1SUKfnbEqbT1/fWcdNmiWgl0C+m3jOnQCQZTiS19W/6XMMtuHWOCAq7Tq8Y+NFE3MLEKNqCTqODgMA+E1SCRCpYjxbmyLEnuCs0sxCARjebqbpm4d2nTiJC,iv:nsiUIWJc5kgg9gxF7m6wSZjiORJZoYlz7W3t/mR86AA=,tag:Kuj0HWKb5NfxVtZ3EDuOuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRm1yZ2NnbDk0U1hYNEJw
            YkNNMHBKY2VKMEk2M0Q1UmlycGYwTVpCK3lzClI2M3RGMWZTaWI1MzhmN3kxZnpm
            dVJmbVREczRKUnhoZHBVeENQVDFoZGcKLS0tIFdIcmtLeG9yTFdRWnp2RTVWbGR3
            WDFYeVB0eWJQSjFQWEhBODRzaHZxS0UKXMJ+sdleP3Bk/HFZ8TcS6oyRgb7Bb1h/
            l4kOqriUluTXGFraIL+hCreYjKFhEf63r45GRIvB/wVAy6my0nRg1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T01:50:59Z"
    mac: ENC[AES256_GCM,data:oFhl+E9UaYKedSJipe2oWamKN9uJg9/MExixlJy4nOHJIgO4VYczxkJ1jG35Ds2aFUTB4Uw7mGEpXrNqtz2uo3QeT5pBGV0WhGuYmNbP1sYoRXCQIDUy3IijrYtzgBaFFS77Ryos+bEPNsG4FjD/IscaVVFSZG/abkAT5hOQ5mI=,iv:A4DCozOCmuoiHOJ+WxGcbji8Ml7J24iFhddmJCrK22o=,tag:ltmJ5ZvjI3cC6BgNCs5UMw==,type:str]
    version: 3.13.3
