apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:Tww7Huwio5qOUZ9Fe8E9km4=,iv:TLaSFgkccR1dprCg7O0vpp6Fs8pXmpE4+4XwQRHlYBE=,tag:J5bhA3C6LWO3ZxVmGPSF5Q==,type:str]
    client_secret: ENC[AES256_GCM,data:Lukj7v2MA43K9VTk7DdQ8t2QrUXtJXXea6y93LUu6rZNuvlb+KbifOSHXP5Ta+yJK9PneeCT07Jb+hQoYsdIuw==,iv:+ZiKFwZz2gRv9qWMxH7/8Lxo77iIbAC5/RBlN3aCmhY=,tag:ZlDhZH0F2Xy27BL39VNi1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVzNrZ1d4R1hGNU0yc25N
            ekVRZmhBc05EN0lZRE1pNkk5Z2I5ZEF6aUM0Ckkzc2xPeUVxdGxodERnZHJNMzV6
            Mjk1anlTcVQ1Y1RVYWJ6UG04T2hhWHcKLS0tIGZEcDZTeTAvQW0zUGlzRjlMOHRk
            YlpCREFJbE9pUCtYaUYxTWRZaHlhWlkKC0C9hrWUGLS4aTr4O2Gc+LvvOSaNv0wj
            M3mgv41AzKgZu+QlPnYLfWpT0bJR4X2QnhegnL3zV+aXsMXmOhmeGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:17:25Z"
    mac: ENC[AES256_GCM,data:dSujFykKxPE1xv7r+bWh7Yy9al2JbqoXU5AYQm6sDI0MEdKtRUwT2cFqM9zUKQXnlZ1mTp1hEE5mBN0PYG0ZLRJ0WTrf4IomQ7qAUFAdQD2qf6HsazXMmxUsV0Yn0mODeiK2Q2p5rmbEiiniEDLRQj87X/gyzphwes/9c5Y8t1M=,iv:JpXMtBHU7JVLsHgdEb+jEKjj9f3cmKb778qJMbPTWcs=,tag:GnSANXw7GxiJP2n1KzTTPQ==,type:str]
    version: 3.13.3
