apiVersion: ENC[AES256_GCM,data:OYU=,iv:6Uzj5KcOWppaTIWJXL5LDI4V8wbQinrrntSI3qSDncc=,tag:cdfs1v4/4CbKjSJSVUL6sA==,type:str]
kind: ENC[AES256_GCM,data:0QPUJWiQ,iv:1F6BRD3M/1X6Fo5y3yiu+1iQKbU1C10gTjI+txiEHUQ=,tag:7UPiMIQhHrcrkZqQQ9s5SA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c3iybL2OAUJ7ktRhV1c=,iv:RdIcgGmK814Ju9u2pSzqe2wRHKuedExk8TxkS+MOAdE=,tag:C/5rGI1ZrNEG2nvKA/yd1g==,type:str]
    namespace: ENC[AES256_GCM,data:nQCB6jAW8kbi,iv:/t0103YUhyWE5PpEJTOvb4Zt5reqny6pacZ3zX0lgIg=,tag:CzvWNZWo6MsJgqcMH33Uug==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:RFRFdokL440L0CHYohOxILc=,iv:3wXwlK8NPim0niCOxwRgs+YUXYLr4KBQO14v7xCuoH8=,tag:1bZweSE8i8kyq7kB8jZn9A==,type:str]
    client_secret: ENC[AES256_GCM,data:TvouK9/CtZzIXg3imW933huGYgigWZJLsaKlbA8pMgJSdRCFwEfmuln4Wi151I6Q+52QDR+BnTvZt6rdgBzBWw==,iv:gLwVu7u4Ig1jG7688bmZG6qhljUNGAdd/olojiK0By0=,tag:M6tXZIQ4YgL2jOIdeLrKiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL0FIek5uMFFOZVNBV3U0
            ajJ5M0Z0VzkwOVBZSVJMcXVpQUVadzJNRFJnClIvZkxuVkRQaWx2S2VUaGdEN1l4
            L0drVmV3QVNEWFUrN3doMlpwdHZmWWMKLS0tIDFaTVRjVDJ2THRHMGZ5REpxZHVM
            T3p0NkhIYm9mMHB4dGVwdUFyN2Q4QU0Ka/2b0QgaUBvCYs9EWsh3IQtZAhvSw81u
            aMSmxH3cOs1fY89RYpV7Ny5fO1PtQ/wyiKQI68cTVjU/Cm8vnlEs+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    lastmodified: "2026-09-25T20:41:26Z"
    mac: ENC[AES256_GCM,data:PYt1zK97B1huIOCkXkzbmTmxMlPnhX2c2BCDA1Wo9DACHFfJsgEzqLv8KoWTpvClg6segdv8/dfFk7LvOc7XiL4r0yHLG2XiQKkeAMy9VIqZcs8px3WKcIh1UWZqRDbZKL63aP214jrtzoNzdgD7sN25yZ9Kanwuu+Irh6C0WgU=,iv:JKlSkWsGrVIb7T6MP/0GhldToAnAxYghCfgkDJx/eF0=,tag:Y6UapS+k+wAL306xOVNdJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
