apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+NFS/77tN5fZCOU9Rt1tSO8=,iv:DTnKIrEhqAcB8tyWkk/d/Qb/iSiG3QCSXUCPj6IIpOE=,tag:Q+rZldrPxGyB0DIltXnCiw==,type:str]
    client_secret: ENC[AES256_GCM,data:Ya7vQcQQFeXs0DmENjMFj7EEm7x+W9NhQX+N4u3TXV1WDi3RaBqcYu9tEybEiYQ8xJlR/naMpgMBPssjoEnlIw==,iv:xMbAzz7EPn7xl4XzXksmBNwAOKyMJ/kjmMAGl0BSrMU=,tag:vhz9wQeVLHc5G+4+3N7dCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY0ZLU2I0STZreGxzeXow
            NXdFMlp6NGM1SE1oQkZkTDFyeVR6eGZHNWdZCmJ4eldKN1JtTjZJOVJuRXl6NElH
            czVNZVlnY2V5WlNKM3ViS3JySEdLTmMKLS0tIHhYNjFlNXJJYVc1bmM3RDNIUXV5
            ZU56M3RUczFrVHBwNlRpb2tqditlMmMKwBl98LUzc4ms6p36/Lm567S9tWe5v4sf
            ZGpj350IJGM73OY1tndt1OCrbbTooqotEwlqULAdmOOmo95va5KTEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T00:02:32Z"
    mac: ENC[AES256_GCM,data:ocfVJd0xKykhEA8xOwTBm7JDCTxoimV8wZjjS/c8URYM0g9/Rhd63fVKM0E6IJiTGMjYE6/sgHm1phST6Zk+sVPy3A8rWL6FpRllQxMHJvvnwEHutj5Sf9spodUy9AkoFNn+CQPfsZ4vPXML6dObpzoZ5ETcqJw+j+DRhdxHAfI=,iv:7zLaT88bGV3rVSRknN1PNcL/4Zno2PQCBW9q+7ztk3s=,tag:2Y+NiZ6OeXy/B/oRQY5B1Q==,type:str]
    version: 3.13.3
