apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:7ezEGRlkf4Y=,iv:ILeg8jzZ/UsUDQtKhZcY31QrSknCYsnZZPj07zizvI0=,tag:EmGlzo/nQDgqRdVQFtcxpQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:nTc7yb58fuV+91Nd+1UPX1BnbmsJWwlDH/wGyVRchtg=,iv:y47i2eG9X/e8LLNoOwPBBtgvi6zxc30qtqs0IZrs4ww=,tag:V2ugPQXEezvG5J1YJAz4ig==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UGlKWWhROTF4UTM2eExl
            UysycnNzWVdzK3JuQWZOU0NRLzRyRjErd2dRCm9ORWpXUmxjcWJFUEFtc25paW9Q
            d3VUeGR4NmtXMFVrT3FSUHcvTkF2akkKLS0tIFdsY3Z1UXZXQTVmcklDWjRubVNz
            em1MM3A3RUEyK3N2L244c1FCTW9QOEEKqWa7T6I/zID0kN+7lAWDs2CnwSE2RQ1m
            Eco/u8R+fpi6IRdAWzrb/tiXWtPAqAPoTixQrbT0ZhCN935qYrKuyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T02:07:19Z"
    mac: ENC[AES256_GCM,data:133j8ZaYG5mpMUtm2GSBQvpr+JW+++UJnAsb6HAGcmsih5UMu//FHbA5qx+LXSB7AtoTIxWcXyyYpMEe1WLlxP8cWZC0c8xN0iWAyyx4rhv7sfjxrjFwoiAyyPyo4BoXK7c0M9Zlp7nrNhnmWCviP5oK78lWPat2EuSFCNrSiLs=,iv:yoJ4d3Tfnb/io2F91iPO51j9WdkImAl7lNXKL6j4R1A=,tag:0LtVjLZ6J5xQaw0bNbl6fw==,type:str]
    version: 3.13.3
