apiVersion: v1
data:
    password: ENC[AES256_GCM,data:hYxsyhBlgyY=,iv:My9L3bQ4OHqq/y6pAlbnqF3A3qZ6cuTamlK6ciUi0pY=,tag:IRJeP8zpIrekr5inUCN4rA==,type:str]
    user: ENC[AES256_GCM,data:Ko2wuATmkzk=,iv:xV9no8Hb8MmCICLdW/hHQV4WdJd84OQU1UQOZeHo9VQ=,tag:LM0sWGMqi1gLbKuY83w7Gw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWmNGVnlxZnlLeWxqNmlt
            QlB5d2tiWUNLTW02ZEdqclA3WGMrUGprTmo4CnpCczFVb1RQQktoTUxXMkdTSGM0
            dnlRSEowUGhraUZ5OVpNUUFmMWY1bEkKLS0tIE0xQWhtKzY1MlRnNXgycFpJc1E0
            NW8raUhZQlVXbCtGOElIcTZDcTVzQmsKauuD4VONNwboutP/1Wi7UlgSrwJV/+i9
            2mA9Fu7jrldQH45tXfwJpGTOLMyd+7U7pASc8kb1y8ZsWh4f/FKn3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T00:48:39Z"
    mac: ENC[AES256_GCM,data:QKnnDkIKEkBDPczBae4ZVvKlYFd0mTbxJZtmbxR3IYlnvypp3lQzAtnfJryfFsTUCZMgkGeMlfHVrNgPLb/nsx5xAYQcpjgtXxLKAO+IHpZAUotF15IRmTCkAIGAPn79ArNAh1OskEGERzizyyZcp1F2LJgA+6TfUxxIruzdma4=,iv:V89K/6ePYuPDHw0ms5YWEyF26P0TyBVLV8ZkB1BOV4A=,tag:ptbBr/NJNKcBaLtzivTFcg==,type:str]
    version: 3.13.3
