apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TCsgMw==,iv:Fgx+ieQFcWI2t/GxN6P2BbHX/1gar5qkgmTr6jBuL5k=,tag:bNXfNcm4je/Uye2xBusWhg==,type:str]
    admin-password: ENC[AES256_GCM,data:Rc2KUa4X6CBa79kzQw0zaPXPV+iRQw==,iv:RM5x2ggUGZj377dVhBjwn+lG1UQmVlL8IMcIyT4CXlQ=,tag:9DsGPYs8/3maPTP3f2KUdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbXRIOHFKaWp3WTRYK1Jm
            YWEydGpsVldkYlRkWUswUzFyRVE1Y05EY1NzCnN5NE9tQ0Y4U0lSSzhjQ3B6a3NW
            T3hjWVgvUHN2NU1oNE9kdnRnUW54MmMKLS0tIHpQdVFPWmx4ZFZ2M3JDNzFvQ3ZY
            VVJBOENkQmZ1UDlUSk5qTFlQd2dpWEEKuLZdUrednNsP5RmtCyOmqvl1PPbZEugp
            jKN5yGM4ytFTmOvXbU0SB8xRHpGHkaZsLFvJV/gY5f/yno+Yjph8ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T19:06:34Z"
    mac: ENC[AES256_GCM,data:TBI3IY3Gvb1jHnkYtYn5H7hnN8aIBSg/ep70hsc5J/Lk5IY+gA6rDhliup1vtSXOrtYa1ke7EIeFRqzika31nq/dJJZ1sXtmmIXZjR+m4jZhKx/LUddM261zIt29EbGIYDpRLSq66R9nv5FGkl2AP9rdG6Pr60L/OMbvMQla5hc=,iv:NjJa9o2xcjxqXtOvLkvPYRg+mWokWcRej17eIiK5R40=,tag:NBVX0pqdOsZsrPd7SMhcfA==,type:str]
    version: 3.13.3
