apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lFarZw==,iv:7KoOfgSOiFMZQeayFe5EKCO3Ir6/yUctXgU77G42W7g=,tag:EzxOXetRWL9l2LPDPa1z7A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:qTqyHYBWN7AAJ+0yibY70yeEebs5qao=,iv:DdTiGQ2d4Q2/eMhY/+W/+WnJqaii6E58go7fYn7xgog=,tag:9lmDN6b09Ao9PVjxbyt/Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRXoyVHI5eVhSTVNtSkIv
            Q3FGM0YyZzJCRGpPUkJpdlo3V3JHR1ZhUEJnCjRVZDA5cnhHMHJTLzJySDVMY0h2
            dE5ySDZuM2M3MFdPTk9VYk5ZN3NWQ28KLS0tIEV0RERBTDU3VHpybFllOWhLelRW
            TkV4QTJnYUk3M1BOZCsvaW9reGsybTQKw0VZ0i+qsmDHl7TfJysBZwCvY9KjNDK9
            wPKS+SS7pWSn7dtpy/u4OxsCrM2F4+xRMvF6bcXtdXM+QrNvAkB5GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T20:11:13Z"
    mac: ENC[AES256_GCM,data:K3MSOWOhIwE5CMjBsYxWaT8zd1pDs8Xaw+QIzJkYdekEZGcfc9fUZBznfsflgHJBoaxyDv1OUeIqinM02oBU4hDkUEPKfRywfHO04HvBc6PQJbQ2S40viSQ61yOJ7NA3AD4U3My0HY7OPOyQbFEk5uswBCQ3yypuaedfUOPPOcM=,iv:T7wqwIBbpyQ6IzPALOLqgma3KmXg/2f539zErw/n+wo=,tag:/4nGkBkYJBNtR4AQXoaxGg==,type:str]
    version: 3.13.3
