apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:p6upTtg3rO1zOk7jtIn92xPJ7s8s/vXY8RifMa442+71543AEDO0pxGEEXxPPBpfdm0XUfywEAM=,iv:1+TTionp5gIa/wLpnIRS4FExT6XSoEJLizBcnZQ3nT8=,tag:jhs6dI7m/z4bWYCz+p1PHg==,type:str]
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzF2NE9qNTFYa0Vvbmw4
            WG5sOVdwS0J6THp4L2lPNENGTzNrM0dnandNCndPUFdaS3dqQ0xXQVA3VDFXdWRJ
            SEY3RW9hUmU1bFdFbnlldDBkMEhmTVkKLS0tIEtDM3dQSmdqOW5DaXpuTTR0MHRa
            MmdLWWp1NVBRc3lXcmdONWI2NFdDbjQKRUcLn1kjRRwkyVhZxqOcwlAlbIa/TOfK
            labrvMQGruSJ8iIhS36BBVaBM3fqTOQnx7qrg79z7ZuO3DUoRKfa0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l78l2gkv78esxqmcglkna905fzrqk6whd6e5ccuplueclmuhdpwqkxd22w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T16:41:48Z"
    mac: ENC[AES256_GCM,data:MkBiNbgF1SMLwTdXkRk85/jYnW7EpRzadFSGUJitIwyNtoL4GqEFexH5lGoMDI7eUkPlTLJXS3S3ZuZN4jGoe6/ryZ/olozTCu6KIcuVpDdsWl9js7wKt3IGhakW6AuDlRpWqRGykOb6YHAETI7dfVmWkgYX0s2WMvKvqbJnbHk=,iv:rXjNhXQ4OKevB35VkAUizAHzfGp2AnU0R7SaCCfqTUs=,tag:f58OmEInxoZ9gRur3dpecw==,type:str]
    version: 3.13.3
